# Generated by Django 3.1.4 on 2021-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfquestions',
            name='docker_file',
            field=models.FileField(blank=True, upload_to='./upload_docker_file'),
        ),
        migrations.AddField(
            model_name='ctfquestions',
            name='docker_type',
            field=models.TextField(blank=True, choices=[('WebFile', 'WebFile'), ('FromDockerHub', 'FromDockerHub')]),
        ),
        migrations.AddField(
            model_name='ctfquestions',
            name='if_docker',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='ctfquestions',
            name='question_ctf_category',
            field=models.CharField(choices=[('', '------'), ('Misc', 'Misc'), ('Android', 'Android'), ('Web', 'Web'), ('PWN', 'PWN'), ('Reverse', 'Reverse'), ('Crypto', 'Crypto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='match_id',
            field=models.IntegerField(blank=True, choices=[(0, '全局通知'), (1, '网鼎杯参赛队伍选拔赛'), (2, 'YoungCtf初赛 & 决赛'), (3, '互联网安全大赛')]),
        ),
    ]
