# Generated by Django 3.1.4 on 2021-01-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0002_auto_20210118_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfquestions',
            name='if_docker',
            field=models.CharField(blank=True, choices=[('是', '1'), ('否', '0')], max_length=1),
        ),
    ]
