# Generated by Django 3.1.4 on 2021-01-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0004_auto_20210118_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctfquestions',
            old_name='docker_path',
            new_name='docker_Hub',
        ),
    ]
