# Generated by Django 3.1.4 on 2021-01-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0005_auto_20210118_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='file_path',
        ),
        migrations.AddField(
            model_name='writeup',
            name='writeup_file',
            field=models.FileField(default='', max_length=255, upload_to='./upload_WriteUp_file'),
        ),
    ]
