# Generated by Django 3.1.4 on 2021-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0006_auto_20210118_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfquestions',
            name='docker_file',
            field=models.FileField(blank=True, upload_to='./upload/upload_docker_file'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='writeup_file',
            field=models.FileField(default='', max_length=255, upload_to='./upload/upload_WriteUp_file'),
        ),
    ]
