# Generated by Django 3.1.4 on 2021-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0008_ctfquestions_if_anticheating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfquestions',
            name='if_AntiCheating',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ctfquestions',
            name='if_docker',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1),
        ),
    ]
