# Generated by Django 3.1.4 on 2021-03-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0011_auto_20210307_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uphistory',
            options={'verbose_name': '选手答题记录及反作弊', 'verbose_name_plural': '选手答题记录及反作弊'},
        ),
        migrations.AddField(
            model_name='uphistory',
            name='match_title',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='uphistory',
            name='user_name',
            field=models.TextField(default=None),
        ),
    ]
