# Generated by Django 3.1.4 on 2021-03-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0012_auto_20210307_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfquestions',
            name='docker_file',
            field=models.FileField(blank=True, upload_to='../static/upload/upload_docker_file', verbose_name='部署到Docker的文件'),
        ),
        migrations.AlterField(
            model_name='ctfquestions',
            name='if_AntiCheating',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=1, verbose_name='是否启用动态flag及反作弊'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_content',
            field=models.CharField(default='暂无简介', max_length=50, verbose_name='竞赛简介'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='竞赛ID'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_name',
            field=models.CharField(default='新建比赛', max_length=40, verbose_name='竞赛名称'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_questions',
            field=models.TextField(verbose_name='竞赛题目'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_start_time',
            field=models.DateTimeField(verbose_name='竞赛开始时间'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_stop_time',
            field=models.DateTimeField(verbose_name='竞赛结束时间'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_user',
            field=models.TextField(verbose_name='参赛选手'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='writeup_file',
            field=models.FileField(default='', max_length=255, upload_to='../static/upload/upload_WriteUp_file'),
        ),
    ]
