# Generated by Django 3.1.4 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0013_auto_20210312_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfquestions',
            name='docker_file',
            field=models.FileField(blank=True, upload_to='static/upload/upload_docker_file', verbose_name='部署到Docker的文件'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='writeup_file',
            field=models.FileField(default='', max_length=255, upload_to='static/upload/upload_WriteUp_file'),
        ),
    ]
