# Generated by Django 3.1.4 on 2021-03-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0014_auto_20210312_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dynamicflag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(verbose_name='比赛ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('question_id', models.IntegerField(verbose_name='题目ID')),
                ('container_id', models.TextField(blank=True, default=None, verbose_name='容器ID')),
                ('container_address', models.TextField(blank=True, default=None, verbose_name='容器地址/端口')),
                ('flag', models.TextField(blank=True, default='', verbose_name='动态Flag')),
            ],
            options={
                'verbose_name': '动态Flag管理',
                'verbose_name_plural': '动态Flag管理',
            },
        ),
    ]
