# Generated by Django 3.1.4 on 2021-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingtai', '0016_auto_20210312_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='match_questions',
            field=models.TextField(max_length=999, verbose_name='竞赛题目'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_user',
            field=models.TextField(max_length=999, verbose_name='参赛选手'),
        ),
    ]
